config/routes.rb
Rails.application.routes.draw do
  root "salary_fits#index"
  resources :salary_fits
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/salary_fit.rb
class SalaryFit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/salary_fits_controller.rb
class SalaryFitsController < ApplicationController
  before_action :set_salary_fit, only: %i[ show edit update destroy ]

  # GET /salary_fits or /salary_fits.json
  def index
    @salary_fits = SalaryFit.all
  end

  # GET /salary_fits/1 or /salary_fits/1.json
  def show
  end

  # GET /salary_fits/new
  def new
    @salary_fit = SalaryFit.new
  end

  # GET /salary_fits/1/edit
  def edit
  end

  # POST /salary_fits or /salary_fits.json
  def create
    @salary_fit = SalaryFit.new(salary_fit_params)

    respond_to do |format|
      if @salary_fit.save
        format.html { redirect_to salary_fit_url(@salary_fit), notice: "Salary fit was successfully created." }
        format.json { render :show, status: :created, location: @salary_fit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @salary_fit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salary_fits/1 or /salary_fits/1.json
  def update
    respond_to do |format|
      if @salary_fit.update(salary_fit_params)
        format.html { redirect_to salary_fit_url(@salary_fit), notice: "Salary fit was successfully updated." }
        format.json { render :show, status: :ok, location: @salary_fit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @salary_fit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salary_fits/1 or /salary_fits/1.json
  def destroy
    @salary_fit.destroy

    respond_to do |format|
      format.html { redirect_to salary_fits_url, notice: "Salary fit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary_fit
      @salary_fit = SalaryFit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def salary_fit_params
      params.require(:salary_fit).permit(:name, :idade, :descricao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/salary_fits_helper.rb
module SalaryFitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalaryFits</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/salary_fits/_form.html.erb
<%= form_with(model: salary_fit) do |form| %>
  <% if salary_fit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(salary_fit.errors.count, "error") %> prohibited this salary_fit from being saved:</h2>

      <ul>
        <% salary_fit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :idade, style: "display: block" %>
    <%= form.text_field :idade %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/salary_fits/_salary_fit.html.erb
<div id="<%= dom_id salary_fit %>">
  <p>
    <strong>Name:</strong>
    <%= salary_fit.name %>
  </p>

  <p>
    <strong>Idade:</strong>
    <%= salary_fit.idade %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= salary_fit.descricao %>
  </p>

</div>

app/views/salary_fits/edit.html.erb
<h1>Editing salary fit</h1>

<%= render "form", salary_fit: @salary_fit %>

<br>

<div>
  <%= link_to "Show this salary fit", @salary_fit %> |
  <%= link_to "Back to salary fits", salary_fits_path %>
</div>

app/views/salary_fits/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="mb-5">[Entrevista SalaryFits] Etapa 2 - Tarefa</h1>

<div id="salary_fits" class="d-flex ms-2">
  <% @salary_fits.each do |salary_fit| %>
    <%= render salary_fit %>
    <p class="me-4">
      <%= link_to "Show this salary fit", salary_fit %>
    </p>
  <% end %>
</div>

<%= link_to "New salary fit", new_salary_fit_path %>

app/views/salary_fits/new.html.erb
<h1>New salary fit</h1>

<%= render "form", salary_fit: @salary_fit %>

<br>

<div>
  <%= link_to "Back to salary fits", salary_fits_path %>
</div>

app/views/salary_fits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @salary_fit %>

<div>
  <%= link_to "Edit this salary fit", edit_salary_fit_path(@salary_fit) %> |
  <%= link_to "Back to salary fits", salary_fits_path %>

  <%= button_to "Destroy this salary fit", @salary_fit, method: :delete %>
</div>